# Generated by Django 4.0.3 on 2022-04-27 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='finalizado_em',
            field=models.DateField(null=True),
        ),
    ]
