# Generated by Django 4.0.3 on 2022-05-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='finalizado_em',
        ),
        migrations.AlterField(
            model_name='registro',
            name='descricao',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
