# Generated by Django 4.0.3 on 2022-05-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='patrimonio',
            field=models.CharField(max_length=10),
        ),
    ]
