# Generated by Django 4.0.3 on 2022-05-22 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='unidade_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='servicos.unidade'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='departamento_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='servicos.departamento'),
        ),
    ]
