# Generated by Django 4.0.3 on 2022-05-14 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_remove_registro_finalizado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='criado_em',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
