# Generated by Django 4.0.3 on 2022-04-27 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_alter_registro_finalizado_em'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='finalizado_em',
        ),
    ]
